Replace current C#-based shim with C version
ScoopInstaller/Shim pull request #3
Opened 2020-01-15 14:55 UTC by gerardog

As stated in lukesampson/scoop#3634,

The current C# based implementation can be replaced by a faster and better solution in C, proposed by @rasa. Its [readme](https://github.com/71/scoop-better-shimexe/blob/master/README.md) explains the benefits. Also closes several issues mentioned in lukesampson/scoop#3634.

This PR uses @rasa code and updates the appveyor build scripts. The build scripts can be improved for sure. Sorry it was my first use of AppVeyor.

2020-01-24 15:29 UTC, gerardog commented
Hi @r15ch13, The build is failing when running a script you added that collects the release notes.
Could you please help me fix it?
Thanks.

2020-01-28 16:59 UTC, Ash258 commented
@ScoopInstaller/maintainers Please create a develop branch when you have time

@gerardog 

- Do not delete code of old shim
	- Just add new src/shim.c with all needed build files
- Rebase to develop after branch creation
	- For local testing it will be better to have them in one place to not always switching branches

This weekend I am finally getting back from Swiss work trip and I will have time for proper review. @gerardog Are you familiar with code or you just copied it from https://github.com/71/scoop-better-shimexe?
As soon as I have my environment we can adjust build and CI related stuff.

2020-01-28 21:39 UTC, gerardog commented
> Just add new src/shim.c with all needed build files

Done @Ash258. Note that the same build scripts fails on a different point on my repo, after collecting the [artifacts](https://ci.appveyor.com/project/gerardog/shim/builds/30417317/artifacts)

> Rebase to develop after branch creation

Sure, waiting for the develop branch to be created. If `new develop`==`current master` then we also could just change the base branch of this PR.

>@gerardog Are you familiar with code or you just copied it 

I just copied it but It looks simple enough so I can give a try if something comes up.

2020-02-03 21:43 UTC, 71 commented
I can also help if there's a problem. We should also find a way to sync changes from https://github.com/71/scoop-better-shimexe to this repo if other changes are made to the binary.

2020-02-09 12:48 UTC, Ash258 requested changes
- Add proper documentation to all functions.
- Format everything as in scoop related projects.
	- https://github.com/lukesampson/scoop/blob/master/.editorconfig
	- Use K&R 0TBS code style

2020-02-09 12:48 UTC, Ash258 commented on build.ps1
> +cmd.exe /c "call `"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars32.bat`" && set > %temp%\vcvars.txt"
Why external cmd??

2020-02-09 12:48 UTC, Ash258 commented on build.ps1
> +& cmd /c cl.exe /O1 /Fe"$build\newshim.exe" "$src\shim.c" '2>&1'
Why external cmd??

2021-11-10 03:36 UTC, Swansoppia commented
> As stated in [ScoopInstaller/Scoop#3634](https://github.com/ScoopInstaller/Scoop/issues/3634),
> 
> The current C# based implementation can be replaced by a faster and better solution in C, proposed by @rasa. Its [readme](https://github.com/71/scoop-better-shimexe/blob/master/README.md) explains the benefits. Also closes several issues mentioned in [ScoopInstaller/Scoop#3634](https://github.com/ScoopInstaller/Scoop/issues/3634).
> 
> This PR uses @rasa code and updates the appveyor build scripts. The build scripts can be improved for sure. Sorry it was my first use of AppVeyor.

2021-11-10 13:45 UTC, gerardog commented
Closing, as I believe scoop team is handling this now.

2021-11-10 13:45 UTC, closed without merging